version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - /home/ubuntu/my-folder/IR/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URLS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  app:
    build: .
    container_name: app
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch